# Generated by Django 4.0 on 2023-09-07 16:45

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='expiration_time',
            field=models.DateTimeField(default=apps.users.utils._create_expiration_date),
        ),
    ]
