# Generated by Django 4.0 on 2023-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_passwordresettoken_user_delete_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='status',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('analyst', 'Аналитик')], max_length=10, verbose_name='статус'),
        ),
    ]
