# Generated by Django 4.0 on 2023-09-08 15:42

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseuser_options_alter_managerprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, validators=[core.utils.validators.allowed_chars_validator], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, validators=[core.utils.validators.allowed_chars_validator], verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, validators=[core.utils.validators.allowed_chars_validator], verbose_name='отчество'),
        ),
    ]
