# Generated by Django 4.0 on 2023-06-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_manager_is_active_alter_manager_user'),
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('is_busy', models.BooleanField(default=False)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.manager')),
            ],
            options={
                'verbose_name': 'assessor',
                'verbose_name_plural': 'assessors',
                'db_table': 'assessors',
            },
        ),
    ]
