# Generated by Django 4.0 on 2023-06-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='is_busy',
            field=models.BooleanField(),
        ),
    ]
