# Generated by Django 4.0 on 2023-07-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
        ('assessors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessor', to='users.manager', verbose_name='менеджер'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='assessors', to='projects.Project', verbose_name='проекты'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='skills',
            field=models.ManyToManyField(to='assessors.Skill', verbose_name='навыки'),
        ),
    ]
