# Generated by Django 4.0 on 2023-06-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0002_alter_assessor_is_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
