# Generated by Django 4.0 on 2023-07-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='skills',
            field=models.ManyToManyField(blank=True, to='assessors.Skill', verbose_name='навыки'),
        ),
    ]
