# Generated by Django 4.0 on 2023-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
        ('assessors', '0003_alter_assessor_is_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessor',
            name='current_project',
        ),
        migrations.AddField(
            model_name='assessor',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
    ]
