# Generated by Django 4.0 on 2023-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0004_remove_assessor_current_project_assessor_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessor',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='assessor',
            name='last_name',
            field=models.CharField(default='asdsad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessor',
            name='middle_name',
            field=models.CharField(default='asdasds', max_length=255),
            preserve_default=False,
        ),
    ]
