# Generated by Django 4.0 on 2023-07-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0005_assessor_blacklist_assessor_second_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessor',
            name='capacity',
        ),
        migrations.CreateModel(
            name='FreeResourceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_hours', models.CharField(max_length=5)),
                ('day_off_hours', models.CharField(max_length=5)),
                ('assessor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='assessors.assessor', verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'время работы в СР',
                'verbose_name_plural': 'времена работы в СР',
                'db_table': 'free_resources_schedule',
            },
        ),
    ]
