# Generated by Django 4.0 on 2023-06-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0005_rename_full_name_assessor_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessor',
            old_name='project',
            new_name='projects',
        ),
    ]
