# Generated by Django 4.0 on 2023-06-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0006_rename_project_assessor_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='username',
            field=models.CharField(error_messages={'unique': 'Исполнитель с таким именем пользователя уже существует.'}, max_length=150, unique=True),
        ),
    ]
