# Generated by Django 4.0 on 2023-06-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_alter_project_date_of_create_and_more'),
        ('users', '0008_alter_code_code_alter_manager_first_name_and_more'),
        ('assessors', '0007_alter_assessor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='date_of_registration',
            field=models.DateField(auto_now_add=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='is_busy',
            field=models.BooleanField(default=False, verbose_name='занят'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.manager', verbose_name='менеджер'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='middle_name',
            field=models.CharField(max_length=255, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='проекты'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='username',
            field=models.CharField(error_messages={'unique': 'Исполнитель с таким именем пользователя уже существует.'}, max_length=150, unique=True, verbose_name='имя пользователя'),
        ),
    ]
