# Generated by Django 4.0 on 2023-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0009_alter_workinghours_friday_alter_workinghours_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='country',
            field=models.CharField(default='Belarus', max_length=255, verbose_name='страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessor',
            name='email',
            field=models.EmailField(default='as@mail.ru', max_length=254, verbose_name='эл. почта'),
            preserve_default=False,
        ),
    ]
