# Generated by Django 4.0 on 2023-07-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_code_code_alter_manager_first_name_and_more'),
        ('assessors', '0009_alter_assessor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='is_free_resource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessor',
            name='max_count_of_second_managers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='second_manager',
            field=models.ManyToManyField(blank=True, related_name='extra', to='users.Manager'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessor', to='users.manager', verbose_name='менеджер'),
        ),
    ]
