# Generated by Django 4.0 on 2023-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_alter_project_date_of_create_and_more'),
        ('users', '0008_alter_code_code_alter_manager_first_name_and_more'),
        ('assessors', '0010_assessor_is_free_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='is_free_resource',
            field=models.BooleanField(default=False, verbose_name='св. ресурс'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='max_count_of_second_managers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. к-во доп. менеджеров'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='assessors', to='projects.Project', verbose_name='проекты'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='second_manager',
            field=models.ManyToManyField(blank=True, related_name='extra', to='users.Manager', verbose_name='Доп. менеджеры'),
        ),
    ]
