# Generated by Django 4.0 on 2023-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0011_alter_assessor_is_free_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='blacklist',
            field=models.BooleanField(default=False, verbose_name='черный список'),
        ),
    ]
