# Generated by Django 4.0 on 2023-08-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0014_remove_assessor_blacklist_assessor_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='причина')),
                ('assessor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='assessors.assessor', verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'уволенный',
                'verbose_name_plural': 'уволенные',
                'db_table': 'fired',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='причина')),
                ('assessor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='assessors.assessor', verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'черный список',
                'verbose_name_plural': 'черные списки',
                'db_table': 'blacklist',
            },
        ),
    ]
