# Generated by Django 4.0 on 2023-08-22 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0016_alter_assessor_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='причина')),
            ],
            options={
                'verbose_name': 'причина добавления в ЧС',
                'verbose_name_plural': 'причины добавления в ЧС',
                'db_table': 'blacklist_reasons',
            },
        ),
        migrations.CreateModel(
            name='FiredReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='причина')),
            ],
            options={
                'verbose_name': 'причина увольнения',
                'verbose_name_plural': 'причины увольнения',
                'db_table': 'fired_reasons',
            },
        ),
        migrations.AddField(
            model_name='blacklist',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fired',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessors.blacklistreason', verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='fired',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessors.firedreason', verbose_name='причина'),
        ),
    ]
