services:
  backend:
    container_name: backend-nest-stage
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.stage
    environment:
      - APP_CONFIG=stage
    command: bash -c "python manage.py migrate --noinput && gunicorn config.wsgi:application -c ../gunicorn.conf.py --bind 0.0.0.0:8000"
    volumes:
      - ./static:/home/nest/backend/src/static
      - ./media:/home/nest/backend/src/media
      - ./backend/db_merge:/home/nest/backend/db_merge
    networks:
      - default_network
    depends_on:
      - postgres
      - celery

  postgres:
    container_name: postgres-nest-stage
    restart: always
    image: postgres:14-alpine3.18
    env_file:
      - ./backend/.env
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    networks:
      - default_network

  redis:
    container_name: redis-nest-stage
    image: redis
    volumes:
      - ./storage/redis_data:/var/lib/redis
    networks:
      - default_network

  celery:
    container_name: celery-nest-stage
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.stage
    env_file:
      - ./backend/.env
    environment:
      - APP_CONFIG=stage
    command: bash -c "celery -A config.celery worker"
    volumes:
      - ./media:/home/nest/backend/src/media
    depends_on:
      - redis
    networks:
      - default_network

  celery-beat:
    container_name: celery-beat-nest-stage
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.stage
    env_file:
      - ./backend/.env
    environment:
      - APP_CONFIG=stage
    command: bash -c "celery -A config.celery beat"
    volumes:
      - ./media:/home/nest/backend/src/media
    depends_on:
      - redis
    networks:
      - default_network

  frontend:
    container_name: frontend-nest-stage
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.stage
    ports:
      - 80:80
      - 443:443
    environment:
      - APP_CONFIG=stage
    volumes:
      - ./certbot/conf:/etc/nginx/cert
      - ./static:/home/nest/backend/src/static
    networks:
      - default_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ -d assessors-test.trainingdata.solutions -m d.bandysik@trainingdta.pro -n --agree-tos

networks:
  default_network: