services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn src.core.wsgi:application --chdir src --bind 0.0.0.0:8000
    volumes:
      - ./backend/src/:/home/assessors/api/src
      - static_volume:/home/assessors/api/src/static
    networks:
      - default_network
    ports:
      - "8000:8000"
    expose:
      - 8000
  postgres:
    image: postgres:15.3-alpine3.18
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assessors
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - default_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/proj/src
      - ./frontend/public:/proj/public
    networks:
      - default_network
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/home/assessors/api/src/static
      - ./nginx/cert:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    networks:
      - default_network
    depends_on:
      - frontend
      - api

volumes:
  static_volume:

networks:
  default_network: