services:
  backend:
    container_name: backend-nest-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - './backend/.env'
    environment:
      - APP_CONFIG=dev
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/src:/backend/src
      - ./backend/src/media:/backend/src/media
      - ./backend/db_merge:/backend/db_merge
    networks:
      - dev_network
    depends_on:
      - postgres
      - celery

  postgres:
    container_name: postgres-nest-dev
    image: postgres:14-alpine3.18
    env_file:
      - './backend/.env'
    expose:
      - 5432
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    networks:
      - dev_network

  redis:
    container_name: redis-nest-dev
    image: redis
    volumes:
      - ./storage/redis-data:/var/lib/redis
    networks:
      - dev_network

  celery:
    container_name: celery-nest-dev
    build: ./backend
    env_file:
      - './backend/.env'
    environment:
      - APP_CONFIG=dev
    command: bash -c "celery -A config.celery worker"
    depends_on:
      - redis
    volumes:
      - ./backend/src/media:/backend/src/media
    networks:
      - dev_network

  celery-beat:
    container_name: celery-beat-nest-dev
    build: ./backend
    env_file:
      - './backend/.env'
    environment:
      - APP_CONFIG=dev
    command: bash -c "celery -A config.celery beat"
    networks:
      - dev_network
    depends_on:
      - redis

networks:
  dev_network: