services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/src/:/home/assessors/backend/src
      - static_volume:/home/assessors/backend/src/static
    networks:
      - default_network
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - postgres
      - celery

  postgres:
    container_name: postgres
    image: postgres:14-alpine3.18
    env_file:
      - './backend/.env'
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - default_network

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    build: ./backend
    env_file:
      - './backend/.env'
    command: bash -c "celery -A core.celery worker --loglevel=info"
    depends_on:
      - redis

  celery-beat:
    container_name: celery-beat
    build: ./backend
    env_file:
      - './backend/.env'
    command: bash -c "celery -A core.celery beat --loglevel=info"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/proj/src
      - ./frontend/public:/proj/public
    networks:
      - default_network

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/home/assessors/backend/src/static
      - ./nginx/cert:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    networks:
      - default_network
    depends_on:
      - frontend
      - api

volumes:
  static_volume:
  redis_data:

networks:
  default_network: