services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: bash -c "python manage.py migrate --noinput && gunicorn config.wsgi:application -c ../gunicorn.conf.py --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/assessors/backend/src/static
      - media_volume:/home/assessors/backend/src/media
      - ./backend/logging:/home/assessors/backend/logging
    expose:
      - 8000
    networks:
      - default_network
    depends_on:
      - postgres
      - celery

  postgres:
    container_name: postgres
    image: postgres:14-alpine3.18
    env_file:
      - ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default_network

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - default_network

  celery:
    container_name: celery
    build: ./backend
    env_file:
      - ./backend/.env
    command: bash -c "celery -A config.celery worker --loglevel=info --logfile=../logging/celery.log"
    volumes:
      - media_volume:/backend/src/media
      - ./backend/logging:/backend/logging
    depends_on:
      - redis
    networks:
      - default_network

  celery-beat:
    container_name: celery-beat
    build: ./backend
    env_file:
      - ./backend/.env
    command: bash -c "celery -A config.celery beat --loglevel=info --logfile=../logging/celery-beat.log"
    volumes:
      - ./backend/logging:/backend/logging
    depends_on:
      - redis
    networks:
      - default_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
       - static_volume:/home/assessors/backend/src/static
    networks:
      - default_network

volumes:
  static_volume:
  redis_data:
  postgres-data:
  media_volume:

networks:
  default_network: