# Generated by Django 4.0 on 2023-07-24 15:46

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Проект с таким названием уже существует.'}, max_length=255, unique=True, verbose_name='название')),
                ('speed_per_hour', models.IntegerField(validators=[core.utils.validators.not_negative_value_validator], verbose_name='Скорость в час')),
                ('price_for_assessor', models.FloatField(validators=[core.utils.validators.not_negative_value_validator], verbose_name='Цена за единицу для ассессора')),
                ('price_for_costumer', models.FloatField(validators=[core.utils.validators.not_negative_value_validator], verbose_name='Цена за единицу для заказчика')),
                ('unloading_value', models.IntegerField(validators=[core.utils.validators.not_negative_value_validator], verbose_name='Объем выгрузок')),
                ('unloading_regularity', models.IntegerField(validators=[core.utils.validators.not_negative_value_validator], verbose_name='Регулярность выгрузок')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('pause', 'На паузе'), ('completed', 'Завершен')], default='active', max_length=10, verbose_name='статус проекта')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='дата старта')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'db_table': 'projects',
            },
        ),
    ]
