# Generated by Django 4.0 on 2023-06-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(error_messages={'unique': 'Проект с таким названием уже существует.'}, max_length=255, unique=True),
        ),
    ]
