# Generated by Django 4.0 on 2023-07-27 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_of_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата старта'),
        ),
    ]
