# Generated by Django 4.0 on 2023-08-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projecttag_project_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
