# Generated by Django 4.0 on 2023-11-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'токен сброса пароля', 'verbose_name_plural': 'токены сброса пароля'},
        ),
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='password_reset_tokens',
        ),
    ]
