# Generated by Django 4.0 on 2023-09-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessor',
            options={'ordering': ['id'], 'verbose_name': 'исполнитель', 'verbose_name_plural': 'исполнители'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id'], 'verbose_name': 'навык', 'verbose_name_plural': 'навыки'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['id'], 'verbose_name': 'рабочие часы', 'verbose_name_plural': 'рабочие часы'},
        ),
    ]
