# Generated by Django 4.0 on 2023-09-08 15:42

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0003_alter_assessor_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='first_name',
            field=models.CharField(max_length=255, validators=[core.utils.validators.allowed_chars_validator], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='last_name',
            field=models.CharField(max_length=255, validators=[core.utils.validators.allowed_chars_validator], verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='middle_name',
            field=models.CharField(max_length=255, validators=[core.utils.validators.allowed_chars_validator], verbose_name='отчество'),
        ),
    ]
