# Generated by Django 4.0 on 2023-09-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0003_alter_assessor_country_alter_assessor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=150, verbose_name='инструмент')),
                ('login', models.CharField(max_length=150, verbose_name='логин')),
                ('password', models.CharField(max_length=150, verbose_name='пароль')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessors.assessor', verbose_name='менеджер')),
            ],
            options={
                'verbose_name': 'учетные данные',
                'verbose_name_plural': 'учетные данные',
                'db_table': 'assessor_credentials',
            },
        ),
    ]
