# Generated by Django 4.0 on 2023-09-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0004_assessorcredentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessorcredentials',
            options={'ordering': ['id'], 'verbose_name': 'учетные данные', 'verbose_name_plural': 'учетные данные'},
        ),
    ]
