# Generated by Django 4.0 on 2023-07-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('assessors', '0004_alter_workinghours_friday_alter_workinghours_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='blacklist',
            field=models.BooleanField(default=False, verbose_name='черный список'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='second_manager',
            field=models.ManyToManyField(blank=True, related_name='extra', to='users.Manager', verbose_name='Доп. менеджеры'),
        ),
    ]
