# Generated by Django 4.0 on 2023-09-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0005_alter_assessorcredentials_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='vacation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата выхода из отпуска'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='state',
            field=models.CharField(choices=[('work', 'Работает'), ('vacation', 'Отпуск'), ('blacklist', 'Черный список'), ('fired', 'Уволен по собственному желанию')], default='work', max_length=10, verbose_name='состояние'),
        ),
    ]
