# Generated by Django 4.0 on 2023-07-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0007_alter_freeresourceschedule_assessor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeresourceschedule',
            options={'verbose_name': 'время работы в СР', 'verbose_name_plural': 'время работы в СР'},
        ),
        migrations.AlterField(
            model_name='freeresourceschedule',
            name='day_off_hours',
            field=models.CharField(max_length=5, verbose_name='выходные дни'),
        ),
        migrations.AlterField(
            model_name='freeresourceschedule',
            name='weekday_hours',
            field=models.CharField(max_length=5, verbose_name='рабочие дни'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='assessor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='assessors.assessor', verbose_name='исполнитель'),
        ),
    ]
