# Generated by Django 4.0 on 2023-09-21 16:59

import apps.assessors.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0007_remove_assessor_is_free_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[apps.assessors.utils.validators.assessor_email_validator], verbose_name='эл. почта'),
        ),
    ]
