# Generated by Django 4.0 on 2023-09-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0008_alter_assessor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessor',
            name='status',
        ),
    ]
