# Generated by Django 4.0 on 2023-07-27 11:11

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0008_alter_freeresourceschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='friday',
            field=models.IntegerField(default=0, validators=[core.utils.validators.not_negative_value_validator, core.utils.validators.day_hours_validator], verbose_name='пятница'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='monday',
            field=models.IntegerField(default=0, validators=[core.utils.validators.not_negative_value_validator, core.utils.validators.day_hours_validator], verbose_name='понедельник'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='saturday',
            field=models.IntegerField(default=0, validators=[core.utils.validators.not_negative_value_validator, core.utils.validators.day_hours_validator], verbose_name='суббота'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='sunday',
            field=models.IntegerField(default=0, validators=[core.utils.validators.not_negative_value_validator, core.utils.validators.day_hours_validator], verbose_name='воскресенье'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='thursday',
            field=models.IntegerField(default=0, validators=[core.utils.validators.not_negative_value_validator, core.utils.validators.day_hours_validator], verbose_name='четверг'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='tuesday',
            field=models.IntegerField(default=0, validators=[core.utils.validators.not_negative_value_validator, core.utils.validators.day_hours_validator], verbose_name='вторник'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='wednesday',
            field=models.IntegerField(default=0, validators=[core.utils.validators.not_negative_value_validator, core.utils.validators.day_hours_validator], verbose_name='среда'),
        ),
    ]
