# Generated by Django 4.0 on 2023-10-17 16:47

import apps.assessors.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0009_remove_assessor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[apps.assessors.utils.validators.assessor_email_validator], verbose_name='эл. почта'),
        ),
    ]
