# Generated by Django 4.0 on 2023-10-17 17:00

import apps.assessors.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0010_alter_assessor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[apps.assessors.utils.validators.assessor_email_validator], verbose_name='эл. почта'),
        ),
    ]
