# Generated by Django 4.0 on 2023-09-07 11:57

import apps.assessors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0015_alter_assessor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='username',
            field=models.CharField(error_messages={'unique': 'Исполнитель с таким именем пользователя уже существует.'}, max_length=150, unique=True, validators=[apps.assessors.validators.assessor_username_validator], verbose_name='имя пользователя'),
        ),
    ]
