# Generated by Django 4.0 on 2023-09-07 13:28

import apps.assessors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0016_alter_assessor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[apps.assessors.validators.assessor_email_validator], verbose_name='эл. почта'),
        ),
    ]
