# Generated by Django 4.2.1 on 2023-05-31 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('is_operational_manager', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='активный')),
                ('operational_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.manager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
                'db_table': 'managers',
            },
        ),
    ]
