# Generated by Django 4.0 on 2023-06-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_code_options_alter_code_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'код подтверждения', 'verbose_name_plural': 'коды подтверждения'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'менеджер', 'verbose_name_plural': 'менеджеры'},
        ),
    ]
