# Generated by Django 4.0 on 2023-06-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_code_options_alter_manager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='is_operational_manager',
            field=models.BooleanField(default=False, verbose_name='операционный менеджер'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='middle_name',
            field=models.CharField(max_length=255, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='operational_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.manager', verbose_name='руководитель'),
        ),
    ]
