# Generated by Django 4.0 on 2023-09-08 20:04

import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_id', models.BigIntegerField(null=True, verbose_name='asana ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('speed_per_hour', models.IntegerField(blank=True, null=True, validators=[core.validators.not_negative_value_validator], verbose_name='Скорость в час')),
                ('price_for_assessor', models.FloatField(blank=True, null=True, validators=[core.validators.not_negative_value_validator], verbose_name='Цена за единицу для ассессора')),
                ('price_for_costumer', models.FloatField(blank=True, null=True, validators=[core.validators.not_negative_value_validator], verbose_name='Цена за единицу для заказчика')),
                ('unloading_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем выгрузок')),
                ('unloading_regularity', models.IntegerField(blank=True, null=True, validators=[core.validators.not_negative_value_validator], verbose_name='Регулярность выгрузок')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pilot', 'Пилот'), ('active', 'В работе'), ('pause', 'На паузе'), ('completed', 'Завершен')], default='active', max_length=10, verbose_name='статус проекта')),
                ('date_of_creation', models.DateField(default=core.utils.current_date, verbose_name='дата старта')),
                ('date_of_completion', models.DateField(blank=True, null=True, verbose_name='дата завершения')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'db_table': 'projects',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'db_table': 'project_tags',
                'ordering': ['id'],
            },
        ),
    ]
