# Generated by Django 4.0 on 2023-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(to='users.ManagerProfile', verbose_name='менеджеры'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='projects.ProjectTag', verbose_name='тег'),
        ),
    ]
