# Generated by Django 4.0 on 2023-09-09 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asana_id',
            field=models.BigIntegerField(verbose_name='asana ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='менеджеры'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pilot', 'Пилот'), ('active', 'В работе'), ('pause', 'На паузе'), ('completed', 'Завершен')], max_length=10, verbose_name='статус проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, to='projects.ProjectTag', verbose_name='тег'),
        ),
    ]
