# Generated by Django 4.0 on 2023-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(to='users.Manager', verbose_name='менеджеры'),
        ),
    ]
