# Generated by Django 4.0 on 2023-09-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'ordering': ['id'], 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
    ]
