# Generated by Django 4.0 on 2023-07-27 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_manager_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 11, 11, 30, 555469), verbose_name='дата старта'),
        ),
    ]
