# Generated by Django 4.0 on 2023-09-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_alter_projecttag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asana_id',
            field=models.BigIntegerField(null=True, verbose_name='asana ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pilot', 'Пилот'), ('active', 'В работе'), ('pause', 'На паузе'), ('completed', 'Завершен')], default='active', max_length=10, verbose_name='статус проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unloading_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем выгрузок'),
        ),
    ]
