# Generated by Django 4.0 on 2023-09-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0003_alter_assessor_country_alter_assessor_email_and_more'),
        ('projects', '0004_projectworkinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkinghours',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_working_hours', to='assessors.assessor', verbose_name='исполнитель'),
        ),
    ]
