# Generated by Django 4.0 on 2023-09-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_asana_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asana_id',
            field=models.BigIntegerField(verbose_name='asana ID'),
        ),
    ]
