# Generated by Django 4.0 on 2023-09-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0009_remove_assessor_status'),
        ('projects', '0007_alter_project_asana_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLoadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('full', 'Полная загрузка'), ('partial', 'Частичная загрузка'), ('reserved', 'Зарезервирован')], max_length=10, verbose_name='статус')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workload_status', to='assessors.assessor', verbose_name='исполнитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'статус загрузки',
                'verbose_name_plural': 'статусы загрузки',
                'db_table': 'workload_statuses',
                'ordering': ['id'],
            },
        ),
    ]
