# Generated by Django 4.0 on 2023-07-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='asana_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='asana ID'),
            preserve_default=False,
        ),
    ]
