# Generated by Django 4.0 on 2023-07-28 08:50

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_asana_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asana_id',
            field=models.BigIntegerField(blank=True, unique=True, verbose_name='asana ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_for_assessor',
            field=models.FloatField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='Цена за единицу для ассессора'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_for_costumer',
            field=models.FloatField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='Цена за единицу для заказчика'),
        ),
        migrations.AlterField(
            model_name='project',
            name='speed_per_hour',
            field=models.IntegerField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='Скорость в час'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unloading_regularity',
            field=models.IntegerField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='Регулярность выгрузок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unloading_value',
            field=models.IntegerField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='Объем выгрузок'),
        ),
    ]
