# Generated by Django 4.0 on 2023-10-03 09:11

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_workloadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asana_id',
            field=models.CharField(max_length=50, verbose_name='asana ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_for_assessor',
            field=models.FloatField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='цена за единицу для ассессора'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_for_costumer',
            field=models.FloatField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='цена за единицу для заказчика'),
        ),
        migrations.AlterField(
            model_name='project',
            name='speed_per_hour',
            field=models.IntegerField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='скорость в час'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unloading_regularity',
            field=models.IntegerField(blank=True, null=True, validators=[core.utils.validators.not_negative_value_validator], verbose_name='регулярность выгрузок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unloading_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='объем выгрузок'),
        ),
    ]
