# Generated by Django 4.0 on 2023-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_asana_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asana_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='asana ID'),
        ),
    ]
