# Generated by Django 4.0 on 2023-10-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unloading_regularity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='регулярность выгрузок'),
        ),
    ]
