# Generated by Django 4.0 on 2023-12-13 13:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_unloading_regularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='speed_per_hour',
            field=models.FloatField(blank=True, null=True, validators=[core.validators.not_negative_value_validator], verbose_name='скорость в час'),
        ),
    ]
