# Generated by Django 4.0 on 2023-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projecttag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True, verbose_name='дата завершения'),
        ),
    ]
