# Generated by Django 4.0 on 2023-07-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessors', '0012_assessor_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_manager', models.CharField(blank=True, max_length=150, null=True, verbose_name='менеджер')),
                ('last_project', models.CharField(blank=True, max_length=255, null=True, verbose_name='последние проекты')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('assessor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='assessors.assessor', verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'db_table': 'blacklist',
            },
        ),
    ]
