# Generated by Django 4.0 on 2023-09-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Добавлен в систему'), ('blacklist', 'Добавлен в ЧС'), ('left', 'Уволен по собственному желанию'), ('returned', 'Возвращен в команду из уволенных'), ('add_manager', 'Закреплен за менеджером'), ('remove_from_manager', 'Удален из команды'), ('add_project', 'Добавлен на проект'), ('remove_project', 'Снят с проекта'), ('add_to_free_resource', 'Добавлен в свободные ресурсы'), ('remove_from_free_resource', 'Удален из свободных ресурсов'), ('add_additional_manager', 'Добавлен доп. менеджер'), ('remove_additional_manager', 'Удален доп. менеджер')], max_length=100, verbose_name='событие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessors.assessor', verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'история',
                'verbose_name_plural': 'истории',
                'db_table': 'history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
