# Generated by Django 4.0 on 2023-08-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessors', '0012_alter_assessor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Исполнитель создан'), ('blacklist', 'Добавлен в ЧС'), ('left', 'Ушел по собств. желанию'), ('returned', 'Перемещен из списка уволенных'), ('add_manager', 'Назначен руководитель'), ('add_project', 'Добавлен на проект'), ('remove_project', 'Снят с проекта'), ('add_additional_project', 'Добавлен на доп. проект'), ('remove_additional_project', 'Снят с доп. проекта'), ('add_to_free_resource', 'Добавлен в СР'), ('remove_from_free_resource', 'Удален из СР'), ('add_additional_manager', 'Добавлен доп. менеджер'), ('remove_additional_manager', 'Удален доп. менеджер')], max_length=100, verbose_name='событие')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessors.assessor', verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'история',
                'verbose_name_plural': 'истории',
                'db_table': 'history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
