# Generated by Django 4.0 on 2023-08-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.CharField(choices=[('created', 'Добавлен в систему'), ('blacklist', 'Добавлен в ЧС'), ('left', 'Уволен по собственному желанию'), ('returned', 'Возвращен в команду из уволенных'), ('add_manager', 'Закреплен за менеджером'), ('remove_from_manager', 'Удален из команды'), ('add_project', 'Добавлен на проект'), ('remove_project', 'Снят с проекта'), ('add_to_free_resource', 'Добавлен в свободные ресурсы'), ('remove_from_free_resource', 'Удален из свободных ресурсов'), ('add_additional_manager', 'Добавлен доп. менеджер'), ('remove_additional_manager', 'Удален доп. менеджер')], max_length=100, verbose_name='событие'),
        ),
    ]
