# Generated by Django 4.0 on 2023-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_history_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата/время'),
        ),
    ]
