# Generated by Django 4.0 on 2023-09-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_history_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('created', 'Создать исполнителя'), ('to_team', 'Забрать в команду'), ('rent', 'Арендовать'), ('add_project', 'Добавить проект'), ('remove_project', 'Удалить с проекта'), ('complete_project', 'Завершить проект'), ('left', 'Уволить'), ('unpin', 'Открепить от себя'), ('add_to_free_resource', 'Отправить в свободные ресурсы'), ('return_from_free_resource', 'Вернуть из свободных ресурсов'), ('to_vacation', 'Отправить в отпуск'), ('from_vacation', 'Вернуть из отпуска')], max_length=30, null=True, verbose_name='действие'),
        ),
    ]
