# Generated by Django 4.0 on 2023-11-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0009_remove_assessor_status'),
        ('history', '0006_alter_history_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='assessors.assessor', verbose_name='исполнитель'),
        ),
    ]
