# Generated by Django 4.0 on 2023-09-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fired', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'ordering': ['id'], 'verbose_name': 'черный список', 'verbose_name_plural': 'черный список'},
        ),
        migrations.AlterModelOptions(
            name='blacklistreason',
            options={'ordering': ['id'], 'verbose_name': 'причина добавления в ЧС', 'verbose_name_plural': 'причины добавления в ЧС'},
        ),
        migrations.AlterModelOptions(
            name='fired',
            options={'ordering': ['id'], 'verbose_name': 'уволенный', 'verbose_name_plural': 'уволенные'},
        ),
        migrations.AlterModelOptions(
            name='firedreason',
            options={'ordering': ['id'], 'verbose_name': 'причина увольнения', 'verbose_name_plural': 'причины увольнения'},
        ),
    ]
