# Generated by Django 4.0 on 2023-08-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fired', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': 'черный список', 'verbose_name_plural': 'черный список'},
        ),
    ]
