# Generated by Django 4.0 on 2023-09-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fired', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='причина')),
                ('blacklist_reason', models.BooleanField(verbose_name='для черного списка')),
            ],
            options={
                'verbose_name': 'причина увольнения',
                'verbose_name_plural': 'причины увольнения',
                'db_table': 'reasons',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fired.reason', verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='fired',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fired.reason', verbose_name='причина'),
        ),
        migrations.DeleteModel(
            name='BlackListReason',
        ),
        migrations.DeleteModel(
            name='FiredReason',
        ),
    ]
