# Generated by Django 4.0 on 2023-09-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fired', '0002_reason_alter_blacklist_reason_alter_fired_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fired',
            name='date_to_return',
            field=models.DateField(blank=True, null=True, verbose_name='дата примерного возвращения'),
        ),
    ]
